const tours = {
  gusar: { icon:"🏔️", ru:["Горы и природа","Гусар","Шахдаг, канатная дорога и невероятные горные виды.","35 AZN",["Выезд из Баку","Красная слобода","Горный комплекс Шахдаг","Возвращение в Баку"]], az:["Dağlar və təbiət","Qusar","Şahdağ, kanat yolu və möhtəşəm dağ mənzərələri.","35 AZN",["Bakıdan yola düşmə","Qırmızı Qəsəbə","Şahdağ kompleksi","Bakıya qayıdış"]], en:["Mountains & nature","Gusar","Shahdag, cable cars and unforgettable mountain views.","35 AZN",["Departure from Baku","Red Village","Shahdag resort","Return to Baku"]] },
  sheki: { icon:"🏛️", ru:["История и культура","Шеки","Ханский дворец, караван-сарай и знаменитая пахлава.","40 AZN",["Выезд из Баку","Дворец шекинских ханов","Старинный караван-сарай","Возвращение в Баку"]], az:["Tarix və mədəniyyət","Şəki","Xan sarayı, karvansara və məşhur Şəki paxlavası.","40 AZN",["Bakıdan yola düşmə","Şəki Xan Sarayı","Qədim karvansara","Bakıya qayıdış"]], en:["History & culture","Sheki","Khan's Palace, caravanserai and famous local baklava.","40 AZN",["Departure from Baku","Sheki Khan's Palace","Historic caravanserai","Return to Baku"]] },
  ismayilli: { icon:"🌲", ru:["Лес и традиции","Исмаиллы","Лагич, ремесленные улочки и тишина горных лесов.","35 AZN",["Выезд из Баку","Подвесной мост","Старинное село Лагич","Возвращение в Баку"]], az:["Meşə və ənənələr","İsmayıllı","Lahıc, sənətkar küçələri və dağ meşələrinin sakitliyi.","35 AZN",["Bakıdan yola düşmə","Asma körpü","Qədim Lahıc kəndi","Bakıya qayıdış"]], en:["Forest & traditions","Ismayilli","Lahij, artisan streets and peaceful mountain forests.","35 AZN",["Departure from Baku","Suspension bridge","Historic Lahij village","Return to Baku"]] },
  gabala: { icon:"🌊", ru:["Озёра и отдых","Габала","Озеро Нохур, Туфандаг и день среди зелёных гор.","40 AZN",["Выезд из Баку","Озеро Нохур","Канатная дорога Туфандаг","Возвращение в Баку"]], az:["Göllər və istirahət","Qəbələ","Nohur gölü, Tufandağ və yaşıl dağlar arasında bir gün.","40 AZN",["Bakıdan yola düşmə","Nohur gölü","Tufandağ kanat yolu","Bakıya qayıdış"]], en:["Lakes & leisure","Gabala","Nohur Lake, Tufandag and a day among green mountains.","40 AZN",["Departure from Baku","Nohur Lake","Tufandag cable car","Return to Baku"]] },
  shamakhi: { icon:"🕌", ru:["История и звёзды","Шамаха","Джума-мечеть, виноградники и знаменитая обсерватория.","35 AZN",["Выезд из Баку","Джума-мечеть","Шамахинская обсерватория","Возвращение в Баку"]], az:["Tarix və ulduzlar","Şamaxı","Cümə məscidi, üzüm bağları və məşhur rəsədxana.","35 AZN",["Bakıdan yola düşmə","Cümə məscidi","Şamaxı Astrofizika Rəsədxanası","Bakıya qayıdış"]], en:["History & stars","Shamakhi","Juma Mosque, vineyards and the famous observatory.","35 AZN",["Departure from Baku","Juma Mosque","Shamakhi Observatory","Return to Baku"]] }
};

const attractions = {
  gusar: ["Горный курорт Шахдаг", "Село Лаза и водопады", "Шахдагский национальный парк", "Гора Базардюзю", "Мавзолей Шейха Джунейда", "Село Хазра", "Мечеть Тадж-Махал", "Краеведческий музей Гусара"],
  sheki: ["Дворец шекинских ханов", "Верхний караван-сарай", "Исторический центр и крепость", "Албанский храм в Кише", "Дом Шекихановых", "Ханская мечеть", "Мастерские шебеке", "Дом народных ремёсел"],
  gabala: ["Курорт Туфандаг", "Озеро Нохур", "Водопад Семь красавиц", "Руины древней Кабалы", "Археологический центр", "Село Нидж и Удинский храм", "Лавандовая ферма", "Габалинский стрелковый клуб"],
  shamakhi: ["Джума-мечеть", "Обсерватория в Пиркули", "Мавзолей Дири-Баба", "Комплекс Едди Гюмбез", "Пиркулинский заповедник", "Село Демирчи", "Винодельня Мейсари", "Дом-музей Мирзы Алекпера Сабира"],
  ismayilli: ["Ремесленное село Лагич", "Историческое село Басгал", "Озеро Гаранохур", "Село Ивановка", "Исмаиллинский заповедник", "Подвесной мост в Зернаве", "Озеро Ашигбайрамлы", "Винодельня Château Monolit"]
};

const ui = {
  ru:{back:"← Назад к турам",duration:"Продолжительность",day:"1 день",departure:"Выезд",time:"08:00 из Баку",price:"Стоимость",program:"Программа поездки",see:"Что увидим за день",book:"Бронирование тура",items:["✓ Транспорт из Баку и обратно","✓ Сопровождение в поездке","✓ Остановки по маршруту"],button:"Забронировать в WhatsApp <span>↗</span>",note:"Ответим и уточним свободную дату",sights:"Что посетить",attractions:"Главные достопримечательности",attractionsCopy:"Лучшие природные, исторические и культурные места региона.",place:"Место для посещения во время путешествия.",message:n=>`Здравствуйте! Хочу забронировать тур: ${n}.`},
  az:{back:"← Turlara qayıt",duration:"Müddət",day:"1 gün",departure:"Çıxış",time:"08:00 Bakıdan",price:"Qiymət",program:"Səyahət proqramı",see:"Bir gündə görəcəklərimiz",book:"Turun rezervasiyası",items:["✓ Bakıdan nəqliyyat və geri dönüş","✓ Səyahət boyu müşayiət","✓ Marşrut üzrə dayanacaqlar"],button:"WhatsApp-da rezerv et <span>↗</span>",note:"Cavab verib uyğun tarixi dəqiqləşdirəcəyik",sights:"Görməli yerlər",attractions:"Əsas görməli yerlər",attractionsCopy:"Regionun ən yaxşı təbiət, tarix və mədəniyyət məkanları.",place:"Səyahət zamanı ziyarət ediləcək məkan.",message:n=>`Salam! ${n} turunu rezerv etmək istəyirəm.`},
  en:{back:"← Back to tours",duration:"Duration",day:"1 day",departure:"Departure",time:"08:00 from Baku",price:"Price",program:"Tour program",see:"What we'll see in one day",book:"Book this tour",items:["✓ Transport from Baku and back","✓ Assistance throughout the trip","✓ Stops along the route"],button:"Book on WhatsApp <span>↗</span>",note:"We'll reply and confirm an available date",sights:"Places to visit",attractions:"Main attractions",attractionsCopy:"The region's best natural, historical and cultural places.",place:"A memorable stop during your journey.",message:n=>`Hello! I would like to book the ${n} tour.`}
};

const params = new URLSearchParams(location.search);
const key = tours[params.get("tour")] ? params.get("tour") : "gusar";
const lang = ["ru","az","en"].includes(params.get("lang")) ? params.get("lang") : (localStorage.getItem("yolda-language") || "ru");
const tour = tours[key]; const data = tour[lang]; const text = ui[lang];
document.documentElement.lang=lang; document.title=`${data[1]} — Road from Baku`;
document.querySelector("#tour-icon").textContent=tour.icon; document.querySelector("#tour-tag").textContent=data[0]; document.querySelector("#tour-name").textContent=data[1]; document.querySelector("#tour-description").textContent=data[2]; document.querySelector("#tour-price").textContent=data[3]; document.querySelector("#booking-price").textContent=data[3];
document.querySelector("#back-link").textContent=text.back; document.querySelector("#duration-label").textContent=text.duration; document.querySelector("#tour-duration").textContent=text.day; document.querySelector("#departure-label").textContent=text.departure; document.querySelector("#tour-departure").textContent=text.time; document.querySelector("#price-label").textContent=text.price; document.querySelector("#program-label").textContent=text.program; document.querySelector("#program-title").textContent=text.see; document.querySelector("#booking-label").textContent=text.book;
document.querySelectorAll(".booking-card li").forEach((item,i)=>item.textContent=text.items[i]); document.querySelector("#booking-note").textContent=text.note; const whatsapp=document.querySelector("#whatsapp-button"); whatsapp.innerHTML=text.button; whatsapp.href=`https://wa.me/994992280705?text=${encodeURIComponent(text.message(data[1]))}`;
document.querySelector("#timeline").innerHTML=data[4].map((item,i)=>`<div class="timeline-item"><span class="timeline-number">0${i+1}</span><div><h3>${item}</h3><p>${text.day}</p></div></div>`).join("");
document.querySelector(".tour-hero").style.backgroundImage=`url("assets/attractions/${key}-hero.jpg")`;
document.querySelector("#attractions-label").textContent=text.sights; document.querySelector("#attractions-title").textContent=text.attractions; document.querySelector("#attractions-copy").textContent=text.attractionsCopy;
document.querySelector("#attractions-grid").innerHTML=attractions[key].map((name,i)=>`<article class="attraction-card"><img src="assets/attractions/${key}-${(i%3)+1}.jpg" alt="${name}" loading="lazy"><div class="attraction-card-content"><span class="attraction-card-number">0${i+1}</span><h3>${name}</h3><p>${text.place}</p></div></article>`).join("");
